import type { AgentProfile, AuditEvent, PolicyRule, VaultSecret } from "./types"

export const agentProfiles: AgentProfile[] = [
  {
    id: "coding-agent",
    name: "Coding Agent",
    did: "did:t3n:748c85e28d07025641ad188fbeeda507aeffd44e",
    role: "Repository automation and pull requests",
    risk: "medium",
    lastSeen: "38s ago",
    status: "verified",
  },
  {
    id: "deploy-agent",
    name: "Deploy Agent",
    did: "did:t3n:9f1a6e3d1d6c49a4f542a882de29a61c0e490111",
    role: "Production deploys and infrastructure tasks",
    risk: "high",
    lastSeen: "2m ago",
    status: "verified",
  },
  {
    id: "research-agent",
    name: "Research Agent",
    did: "did:t3n:3ddca106a77844b8b4a133ccbc9187fd841e02cc",
    role: "External research and document retrieval",
    risk: "low",
    lastSeen: "5m ago",
    status: "watching",
  },
  {
    id: "finance-agent",
    name: "Finance Agent",
    did: "did:t3n:0e1ad7a9867b4f9ea8709dbec555e710f302b22a",
    role: "Billing, invoices, and payment checks",
    risk: "high",
    lastSeen: "11m ago",
    status: "verified",
  },
]

export const vaultSecrets: VaultSecret[] = [
  {
    id: "github",
    label: "GitHub token",
    provider: "GitHub",
    fingerprint: "ghp_...7c9a",
    rotation: "7 days",
    storedIn: "z:<tid>:secrets",
    host: "api.github.com",
  },
  {
    id: "aws",
    label: "AWS deploy role",
    provider: "AWS STS",
    fingerprint: "arn:aws:iam::...:role/deploy",
    rotation: "30 minutes",
    storedIn: "z:<tid>:secrets",
    host: "sts.amazonaws.com",
  },
  {
    id: "openai",
    label: "OpenAI API key",
    provider: "OpenAI",
    fingerprint: "sk-proj-...vaulted",
    rotation: "14 days",
    storedIn: "z:<tid>:secrets",
    host: "api.openai.com",
  },
  {
    id: "mongodb",
    label: "MongoDB URI",
    provider: "MongoDB Atlas",
    fingerprint: "mongodb+srv://...cluster",
    rotation: "30 days",
    storedIn: "z:<tid>:secrets",
    host: "mongodb.net",
  },
  {
    id: "cloudinary",
    label: "Cloudinary API secret",
    provider: "Cloudinary",
    fingerprint: "cld_...vaulted",
    rotation: "30 days",
    storedIn: "z:<tid>:secrets",
    host: "api.cloudinary.com",
  },
  {
    id: "stripe",
    label: "Stripe restricted key",
    provider: "Stripe",
    fingerprint: "rk_live_...19fd",
    rotation: "24 hours",
    storedIn: "z:<tid>:secrets",
    host: "api.stripe.com",
  },
]

export const policyRules: PolicyRule[] = [
  {
    id: "pol_coding_github",
    agentId: "coding-agent",
    resource: "github",
    allowed: true,
    requiresApproval: false,
    ttlMinutes: 30,
    scopes: ["repo:write", "pull_request:read", "workflow:dispatch"],
    allowedHosts: ["api.github.com"],
    terminalFunction: "issue-temp-credential",
  },
  {
    id: "pol_deploy_aws",
    agentId: "deploy-agent",
    resource: "aws",
    allowed: true,
    requiresApproval: true,
    ttlMinutes: 15,
    scopes: ["sts:AssumeRole", "cloudformation:deploy", "s3:put-object"],
    allowedHosts: ["sts.amazonaws.com", "cloudformation.amazonaws.com", "s3.amazonaws.com"],
    terminalFunction: "issue-temp-credential",
  },
  {
    id: "pol_research_openai",
    agentId: "research-agent",
    resource: "openai",
    allowed: true,
    requiresApproval: false,
    ttlMinutes: 20,
    scopes: ["responses:create", "models:read"],
    allowedHosts: ["api.openai.com"],
    terminalFunction: "proxy-with-placeholders",
  },
  {
    id: "pol_finance_stripe",
    agentId: "finance-agent",
    resource: "stripe",
    allowed: true,
    requiresApproval: true,
    ttlMinutes: 10,
    scopes: ["payment_intents:read", "customers:read"],
    allowedHosts: ["api.stripe.com"],
    terminalFunction: "issue-temp-credential",
  },
  {
    id: "pol_research_aws",
    agentId: "research-agent",
    resource: "aws",
    allowed: false,
    requiresApproval: true,
    ttlMinutes: 0,
    scopes: [],
    allowedHosts: [],
    terminalFunction: "deny",
  },
]

export const auditEvents: AuditEvent[] = [
  {
    id: "evt_01",
    time: "12:42:10",
    actor: "deploy-agent",
    action: "Terminal3 verified agent DID",
    resource: "did:t3n:9f1a...0111",
    status: "verified",
    txHash: "0x4f83...a12c",
  },
  {
    id: "evt_02",
    time: "12:42:13",
    actor: "deploy-agent",
    action: "Policy check requested",
    resource: "aws",
    status: "needs_approval",
    txHash: "0x6e71...91dd",
  },
  {
    id: "evt_03",
    time: "12:42:19",
    actor: "human-owner",
    action: "Approved production deploy scope",
    resource: "aws",
    status: "approved",
    txHash: "0x87ab...f012",
  },
  {
    id: "evt_04",
    time: "12:42:22",
    actor: "AgentVault",
    action: "Issued temporary credential reference",
    resource: "aws",
    status: "sealed",
    txHash: "0x992e...45bb",
  },
  {
    id: "evt_05",
    time: "12:43:01",
    actor: "AgentVault",
    action: "Revoked expired GitHub reference",
    resource: "github",
    status: "revoked",
    txHash: "0x12aa...771c",
  },
]
